# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lock.proto',
  package='lock',
  syntax='proto3',
  serialized_options=_b('\242\002\003HLW'),
  serialized_pb=_b('\n\nlock.proto\x12\x04lock\"\'\n\x07Request\x12\x0e\n\x06pubKey\x18\x01 \x01(\t\x12\x0c\n\x04sign\x18\x02 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06ranStr\x18\x01 \x01(\t22\n\x04Lock\x12*\n\x07\x64\x65\x63rypt\x12\r.lock.Request\x1a\x0e.lock.Response\"\x00\x42\x06\xa2\x02\x03HLWb\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='lock.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pubKey', full_name='lock.Request.pubKey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign', full_name='lock.Request.sign', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=59,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='lock.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ranStr', full_name='lock.Response.ranStr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'lock_pb2'
  # @@protoc_insertion_point(class_scope:lock.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'lock_pb2'
  # @@protoc_insertion_point(class_scope:lock.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_LOCK = _descriptor.ServiceDescriptor(
  name='Lock',
  full_name='lock.Lock',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=89,
  serialized_end=139,
  methods=[
  _descriptor.MethodDescriptor(
    name='decrypt',
    full_name='lock.Lock.decrypt',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCK)

DESCRIPTOR.services_by_name['Lock'] = _LOCK

# @@protoc_insertion_point(module_scope)
